# Generated by Django 5.0.4 on 2024-05-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_create_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create_profile'
        ),
    ]
