# Generated by Django 5.0.4 on 2024-05-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_subscriber_delete_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='latency',
            field=models.FloatField(default=0.0),
        ),
    ]
